version: "3"
services:
    mildom-live-feed:
        build:
            context: .
            dockerfile: Dockerfile
        image: mildom-live-feed
        ports:
            - "${APP_PORT:-80}:8000"
        volumes:
            - '.:/app'
